### ISSUE TITLE
Create a VSCode Headlamp plugin

### ISSUE THREAD

**Issue by joaquimrocha** [kubernetes-sigs/headlamp#1207]
VSCode is widely used and we want to leverage that in order to make it easier to onboard developers (especially new ones) to Headlamp.
Therefore, we should have a plugin for VSCode, called Headlamp, with the following capabilities:

- [x] Provide options for creating a new Headlamp plugin
- [x] Run Headlamp from an existing clone (and offer to clone it if it doesn't exist)

_Optional:_
- [ ] Install Headlamp in-cluster (using kubectl)

**Comment by illume** [comment]
There's a preview release inside vscode.

- https://github.com/headlamp-k8s/vscode-extension-headlamp
- https://marketplace.visualstudio.com/items?itemName=headlamp.headlamp&ssr=false#overview

**Comment by illume** [comment]
@joaquimrocha I addressed the issues from the vscode extension review the other day.

- [x] Show instructions for how to use it. 
  - [x] make screenshot for readme
- [x] remove debug message on "Create new plugin", shows "hello" message
- [x] check if headlamp is in home folder, not just vscode workspace.
- [x] bug when no workspace files
  - [x] show a message "You have not yet opened a folder"


Here:
- https://github.com/headlamp-k8s/vscode-extension-headlamp
- https://marketplace.visualstudio.com/items?itemName=headlamp.headlamp&ssr=false#overview

**Comment by illume** [comment]
The main points of this issue are done, any further work can be done in other issues... so closing.
