### ISSUE TITLE
Review & complete exposed information in resources' list and details view

### ISSUE THREAD

**Issue by joaquimrocha** [kubernetes-sigs/headlamp#173]
**Description**
The resources list and details show some information related to the resources, but not all the useful information is showing.
We need to review what's missing from each list + details views, for all resources, and either add them (if they're trivial), or ask Design to mock things for us (if they're complex).
This includes but it's not limited to: pods list that are related to some resources/objects and should be added to their details' views; related objects that should be linked from each other's views; resource's own information (i.e. from its YAML info) that may be missing; etc.

This issue should be an umbrella for more individual issues that mention what needs to be actually implemented.

**Individual changes:**
Pod details view:
- [x] Add link to owner (controller)
- [x] Add link to the node a pod is running on (#254)
- [x] Add volumes section with type + name
- [ ] Add metrics, status, mounts, ports, liveness/readiness probes, and volume mounts to each container displayed

Pod, DaemonSet list view:
- [x] Add owner (controller) column (#254)

Deployment details:
- [x] Remove container section and add owned pods(#343 )

RoleBinding details:
- [ ] Link to the Role or ClusterRole that's bound

More changes TBD

**Comment by illume** [comment]
Closing this issue because it's mostly marked as done, is very old, and out of date. If another review of these things is wanted a new issue can be opened.
