### ISSUE TITLE
Implement a graph / observability view

### ISSUE THREAD

**Issue by joaquimrocha** [kubernetes-sigs/headlamp#198]
Graph views are useful for a quick, visual representation of the relation between cluster resources. Moreover, we can use information from tools like Inspektor Gadget to implement observability on top of it.

Deps:
* [x] Add a graph view: #2225 
* [x] Add the ability for plugins to change the graph
* [x] Add observability via a plugin

**Comment by illume** [comment]
@sniok I think this issue can be closed?

This observability task is I guess tracked as part of the inspektor gadget plugin? 

> Add observability via a plugin

Is there another issue for this work? I guess we can close this issue and drop the link to it here.

**Comment by illume** [comment]
This is done I think.
