### ISSUE TITLE
Map issues and improvements

### ISSUE THREAD

**Issue by sniok** [kubernetes-sigs/headlamp#2519]
After review there were a couple of non-blocking issues/improvements found in #2225 that would need to be addressed:

- [x]  Improve initial loading behavior, resources should load at once if possible: Thottled every 500ms. Done in https://github.com/headlamp-k8s/headlamp/pull/2225
- [ ]  Improve how empty state is displayed on resource picker button
- [x]  Make resource picker button and popup accessible Done in https://github.com/headlamp-k8s/headlamp/pull/2225
- [x]  Fix some issues with state in query params #2600
- [x]  Fix: Sometimes clicking on Home breadcrumb doesn't take you home. It is leaving the namespace filter set to the namespace I was in with no breadcrumbs visible.
- [x] Reduce CPU usage #2538
- [x]  Improve Map behavior when resizing after manual panning https://github.com/headlamp-k8s/headlamp/pull/2649
- [ ]  Improve behavior with browser zoom-in
- [x]  Border of the details panel disappears sometimes #2629
![image](https://github.com/user-attachments/assets/5350268a-8706-4fa2-86ef-b93d8d1250ca)
